name: Sync Odin Legit Releases

on:
  schedule:
    - cron: '0 0 * * *' # Runs once a day at midnight
  workflow_dispatch: # Lets you run manually

jobs:
  sync-releases:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your repo
        uses: actions/checkout@v4

      - name: Get latest legit release
        run: |
          # Get the latest release info
          LATEST_RELEASE=$(curl -s https://api.github.com/repos/odtheking/Odin/releases/latest | jq -r '.tag_name')
          echo "Latest release: $LATEST_RELEASE"

          # Find the right .jar file (exclude "odinclient")
          ASSET_URL=$(curl -s https://api.github.com/repos/odtheking/Odin/releases/latest | jq -r '.assets[] | select(.name | endswith(".jar") and contains("odinclient") | not) | .browser_download_url')

          if [ -z "$ASSET_URL" ]; then
            echo "No legit .jar file found in the latest release"
            exit 0
          fi

          # Download the legit .jar if it's not already there
          wget -N "$ASSET_URL"

      - name: Commit and push if new release
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "your-email@example.com"
          git add .
          if ! git diff --cached --quiet; then
            git commit -m "Update Odin Legit Release - $(date)"
            git push
          else
            echo "No new release to commit"
          fi
