name: Sync Odin Legit Version

on:
  schedule:
    - cron: '0 0 * * *' # Runs once a day at midnight
  workflow_dispatch: # Lets you run it manually from Actions

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your repo
        uses: actions/checkout@v4

      - name: Sync from original Odin repo
        run: |
          git clone --depth 1 --branch main https://github.com/odtheking/Odin.git temp-odin
          rsync -av --exclude='OdinClient/' temp-odin/ .
          rm -rf temp-odin

      - name: Commit and push if changes exist
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "your-email@example.com"
          git add .
          if ! git diff --cached --quiet; then
            git commit -m "Sync Odin Legit Version - $(date)"
            git push
          else
            echo "No changes to commit"
          fi
