name: Sync Odin Legit Releases

on:
  schedule:
    - cron: '0 0 * * *' # Runs once a day at midnight
  workflow_dispatch: # Lets you run manually

jobs:
  sync-releases:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your repo
        uses: actions/checkout@v4

      - name: Get latest release
        run: |
          LATEST_RELEASE=$(curl -s https://api.github.com/repos/odtheking/Odin/releases/latest | jq -r '.tag_name')
          echo "Latest release: $LATEST_RELEASE"

          ASSET_URL=$(curl -s https://api.github.com/repos/odtheking/Odin/releases/latest | jq -r '.assets[] | select(.name | endswith(".jar")) | .browser_download_url')

          if [ -z "$ASSET_URL" ]; then
            echo "No .jar files found in latest release"
            exit 0
          fi

          wget -N "$ASSET_URL"

      - name: Commit and push if new release
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "your-email@example.com"
          git add .
          if ! git diff --cached --quiet; then
            git commit -m "Update Odin Legit Release - $(date)"
            git push
          else
            echo "No new release to commit"
          fi
